// The public types of `jrs-swp`, hand-written.
//
// `binding.d.ts` beside this file is generated by napi-rs from the Rust
// signatures and is overwritten by every build, so it cannot carry the two things
// only the loader knows: the exception class, which is defined in JavaScript
// because a native addon cannot extend the built-in `Error`, and the fact that the
// entry point re-exports the addon *by name*. That list is the package's surface,
// and it is deliberately narrower than the binary's — `installErrorFactory` is the
// seam between `index.js` and the addon, `ProtectTask`/`ScanTask` are napi's
// registration handles with no constructor, and `__napiBindingTarget` says which
// artifact the loader happened to load. A caller who types against the addon gets
// names that do not exist at the entry point, so this file re-exports each name
// `index.js` exports and nothing else. `tests/surface.test.mjs` holds the runtime
// half of that promise; a new export that reaches the binary without passing here
// fails the suite, and a name declared here that the loader never re-exports fails
// `tsc`.
//
// One thing the types cannot express, so it is stated where a caller will read it:
// every operation that is synchronous *throws*, and the two asynchronous ones —
// `protectSummary` and `scan` — *reject*. A `catch` block around an `await`
// therefore sees both kinds, and a caller who writes only `.catch()` on
// `Session.open` has an error handler that never runs.
//
// The fields of `SwpError` are declared writable because they are: the loader
// assigns them as plain own properties on the object it throws. `readonly` would
// be a nicer promise and a false one, and a caller who copies an envelope into
// their own error type would be told a lie by the compiler.

export {
  BINDING_VERSION,
  InitOutcome,
  Report,
  SWP_VERSION,
  ScanOutcome,
  Session,
  StoredReport,
  VerifyOutcome,
  banner,
  capabilities,
  errorCodes,
  reportStem,
  suggestSites
} from './binding'

export type {
  AdapterUse,
  Candidate,
  Capabilities,
  DefaultPolicy,
  EvidenceItem,
  GeneratorInfo,
  InitOptions,
  InitResult,
  LanguageInfo,
  Limits,
  Measurement,
  Overrides,
  ProjectIdentity,
  ProtectConfig,
  ProtectedFile,
  ProtectedSite,
  ProtectOptions,
  ProtectSummary,
  PublicKeys,
  RefusalCount,
  RefusedSite,
  Region,
  ReleaseRecord,
  ReleaseSelection,
  ReleaseTally,
  Run,
  SavedReport,
  ScannedSite,
  Settings,
  SiteRange,
  SiteRow,
  SwpConfig,
  TagRange,
  VerifyOptions,
  WatermarkParams
} from './binding'

/**
 * The only error this package raises, for every failure the SDK reports and for a
 * panic that reached the boundary.
 *
 * `message` is the SDK's own sentence and `code` is the stable half of the
 * contract — the field to branch on, against the table `errorCodes()` publishes.
 * There is no subclass per code: codes are data, and a hierarchy would be a second
 * taxonomy this binding would then have to keep in step with the Rust one.
 *
 * `path` is set when the failure named a file the store holds (forward-slashed and
 * store-relative), and `causedBy` when there was a lower-cause to give. Both are
 * `null` rather than absent, so reading an envelope never depends on a key
 * existing. `rendered` is the whole block a terminal user would have read — code,
 * sentence, next step — kept so a foreign process can print it verbatim instead of
 * composing its own.
 *
 * A caller never constructs one; the signature is here because the class is
 * exported, and `instanceof` is how a `catch` block decides an SWP-1 failure is
 * what it caught.
 */
export declare class SwpError extends Error {
  name: 'SwpError'
  /** The SDK's code, as the Rust table spells it: `'NOT_PROTECTED'`, `'IO_ERROR'`. */
  code: string
  /** The sentence the command would have printed. */
  message: string
  /** Store-relative and forward-slashed, or `null` when no store entry is meant. */
  path: string | null
  /** A lower-cause sentence, or `null`. */
  causedBy: string | null
  /** What to do next, in one sentence. Never empty. */
  nextStep: string
  /** Code, sentence, cause and next step, as one block of text. */
  rendered: string

  constructor (
    code: string,
    message: string,
    path: string | null,
    causedBy: string | null,
    nextStep: string,
    rendered: string
  )
}
