/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/** The build this binding drives, in the words a report's `generator` uses. */
export declare function banner(): string

/** Lets the JS loader hand the addon its `SwpError` constructor. */
export declare function installErrorFactory(ctor: new (code: string, message: string, path: string | null, causedBy: string | null, nextStep: string, rendered: string) => Error): void

export declare function probeAsync(mode: string): Promise<unknown>

/**
 * Probe: a synchronous failure arrives as the factory's object, not a
 * napi-synthesized `Error`.
 */
export declare function probeThrow(code: string): string
