//! Secret newtypes. The invariants that matter here are all negative: these
//! types cannot be printed, cannot be serialized, and erase themselves.

use zeroize::Zeroizing;

use crate::ROOT_SECRET_LEN;
use swp_core::error::{ErrorCode, SwpError};

/// Keyed with a public constant, so `RootSecret::fingerprint` is a one-way
/// handle on the key rather than a derivation of it. Frozen: changing it
/// re-labels every key an owner has ever written down.
const CHECK_VALUE_LABEL: &[u8] = b"SWP-1/key-fingerprint/v1";

/// Variable-length key material that erases itself.
///
/// Deliberately: no `Display`, no `Serialize`, no `Clone`, and a `Debug` impl
/// that reports only the length. A `clone` would leave an unzeroized copy in
/// memory and make accidental leaks much easier.
pub struct SecretBytes(Zeroizing<Vec<u8>>);
impl SecretBytes {
    pub fn from_vec(v: Vec<u8>) -> Self {
        SecretBytes(Zeroizing::new(v))
    }

    pub fn from_slice(v: &[u8]) -> Self {
        SecretBytes(Zeroizing::new(v.to_vec()))
    }

    pub fn len(&self) -> usize {
        self.0.len()
    }

    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// Read-only access for the derivation functions in this crate. Not
    /// exported: once bytes leave here they are no longer zeroized.
    pub(crate) fn as_slice(&self) -> &[u8] {
        &self.0
    }
}

impl std::fmt::Debug for SecretBytes {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "SecretBytes([REDACTED {} bytes])", self.0.len())
    }
}

/// The 256-bit root of trust for one project identity. Generated by the OS
/// CSPRNG, sealed at rest, never written into source, manifests, reports, logs
/// or error values.
pub struct RootSecret(SecretBytes);

impl RootSecret {
    pub fn from_bytes(b: &[u8]) -> Result<Self, SwpError> {
        if b.len() != ROOT_SECRET_LEN {
            return Err(SwpError::new(
                ErrorCode::SecretUnavailable,
                format!(
                    "root secret must be exactly {ROOT_SECRET_LEN} bytes, found {}",
                    b.len()
                ),
            ));
        }
        Ok(RootSecret(SecretBytes::from_slice(b)))
    }

    pub fn from_secret(s: SecretBytes) -> Result<Self, SwpError> {
        Self::from_bytes(s.as_slice())
    }

    pub(crate) fn as_slice(&self) -> &[u8] {
        self.0.as_slice()
    }

    /// Whether two loaded secrets are the same key.
    ///
    /// Deliberately the only way to compare root secrets without exposing
    /// bytes: `swp init` must be able to say "the secret you just supplied is
    /// the one already in this store" without ever handing either one to
    /// caller-owned memory, and a caller that could compare raw bytes would
    /// also be a caller that could log them.
    pub fn same_as(&self, other: &RootSecret) -> bool {
        crate::derive::constant_time_eq(self.as_slice(), other.as_slice())
    }

    /// A short, non-secret handle for a key: the first 40 bits of
    /// `HMAC(key = CHECK_VALUE_LABEL, message = secret)`. The public label is the
    /// HMAC key and the secret is the message, so this is a check value of the
    /// secret rather than a MAC of a constant under it. Lets `swp inspect` and
    /// `swp init` say "this store uses key 3fqz2-…" so a restored backup can be
    /// recognised as the right one, without any path from the printed value back
    /// to the key.
    pub fn fingerprint(&self) -> String {
        use hmac::{Hmac, Mac};
        use sha2::Sha256;
        let mut mac = Hmac::<Sha256>::new_from_slice(CHECK_VALUE_LABEL)
            .expect("label length is valid for HMAC");
        mac.update(self.as_slice());
        let out = mac.finalize().into_bytes();
        swp_core::id::base32_lower(&out[..5])
    }
}

impl std::fmt::Debug for RootSecret {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "RootSecret([REDACTED])")
    }
}

/// A single-purpose key derived from the root secret. The domain is recorded so
/// a key can never be replayed into the wrong derivation, and is checked by
/// [`crate::derive::keyed`].
pub struct DerivedKey {
    bytes: SecretBytes,
    domain: &'static str,
}

impl DerivedKey {
    pub(crate) fn new(bytes: SecretBytes, domain: &'static str) -> Self {
        DerivedKey { bytes, domain }
    }

    pub(crate) fn as_slice(&self) -> &[u8] {
        self.bytes.as_slice()
    }

    /// The domain this key belongs to.
    pub fn domain(&self) -> &'static str {
        self.domain
    }
}

impl std::fmt::Debug for DerivedKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "DerivedKey({} [REDACTED])", self.domain)
    }
}

/// The public halves of a project's keypair. Safe to commit and to ship.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct PublicKeys {
    /// Base64 Ed25519 verify key. Distributed with the public manifest so a
    /// third party can check that a release record was not edited after the
    /// fact.
    pub verify_key_b64: String,
    /// Which scheme produced it, so a future SWP-2 cannot be mistaken for this.
    pub algorithm: String,
}

impl PublicKeys {
    pub fn new(verify_key: &[u8; 32]) -> Self {
        use base64::Engine as _;
        PublicKeys {
            verify_key_b64: base64::engine::general_purpose::STANDARD.encode(verify_key),
            algorithm: "ed25519".to_string(),
        }
    }

    pub fn verify_key_bytes(&self) -> Result<[u8; 32], SwpError> {
        if self.algorithm != "ed25519" {
            return Err(SwpError::unsupported_version(0, 1).caused_by(format!(
                "unsupported signature algorithm {:?}",
                self.algorithm
            )));
        }
        use base64::Engine as _;
        let raw = base64::engine::general_purpose::STANDARD
            .decode(&self.verify_key_b64)
            .map_err(|e| SwpError::invalid_manifest(format!("verify key is not base64: {e}")))?;
        if raw.len() != 32 {
            return Err(SwpError::invalid_manifest("verify key must be 32 bytes"));
        }
        let mut k = [0u8; 32];
        k.copy_from_slice(&raw);
        Ok(k)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn secrets_redact_themselves_in_debug() {
        let s = SecretBytes::from_slice(b"0123456789abcdef0123456789abcdef");
        let rendered = format!("{s:?}");
        assert!(rendered.contains("REDACTED"));
        assert!(!rendered.contains("0123456789"));
        let r = RootSecret::from_bytes(&[0xaau8; 32]).unwrap();
        let rendered = format!("{r:?}");
        assert_eq!(rendered, "RootSecret([REDACTED])");
        assert!(!rendered.contains("aa"));
    }

    #[test]
    fn root_secret_rejects_wrong_length() {
        assert!(RootSecret::from_bytes(&[0u8; 31]).is_err());
        assert!(RootSecret::from_bytes(&[0u8; 64]).is_err());
        assert!(RootSecret::from_bytes(&[0u8; 32]).is_ok());
    }

    #[test]
    fn keys_compare_and_fingerprint_without_revealing_themselves() {
        let a = RootSecret::from_bytes(&[0x11u8; 32]).unwrap();
        let b = RootSecret::from_bytes(&[0x11u8; 32]).unwrap();
        let c = RootSecret::from_bytes(&[0x12u8; 32]).unwrap();
        assert!(a.same_as(&b));
        assert!(!a.same_as(&c));
        assert_eq!(a.fingerprint(), b.fingerprint());
        assert_ne!(a.fingerprint(), c.fingerprint());
        // The handle is short and alphabet-restricted, and carries no more of
        // the key than its own length.
        assert_eq!(a.fingerprint().len(), 8);
        assert!(!a.fingerprint().contains("aa"));
    }

    #[test]
    fn public_keys_round_trip_and_reject_foreign_algorithms() {
        let pk = PublicKeys::new(&[7u8; 32]);
        assert_eq!(pk.verify_key_bytes().unwrap(), [7u8; 32]);
        let mut bad = pk.clone();
        bad.algorithm = "dsa".into();
        assert!(bad.verify_key_bytes().is_err());
        let mut short = pk.clone();
        short.verify_key_b64 = "AAAA".into();
        assert!(short.verify_key_bytes().is_err());
    }
}
